window.SLIDES = [
"Credit Where It's Due",
"An email, circa 2003",
"The first page of my thesis",
"This Is Not a Story About a Hard Advisor",
"Here Is What I Actually Remember",
"He wasn't the gift. They were.",
"Hard Circumstances Don't Deserve the Credit",
"We see versions of this in biology",
"The Pathogen Is Not a Gift Either",
"But the System Is Not Passive",
"Trained Immunity",
"The threat doesn't get the credit. The response does.",
"Which Brings Me to the Last Eighteen Months",
"On Policy Alone, This Should Have Been a Lost Year",
"But that is not what happened here",
"Already Connected, but Not Yet Finished",
"Whatever Comes Next, There Is Strength in Numbers",
"What the people in this department actually did",
"Blue Ridge NIH Ranking",
"That Ranking Did Not Move on Its Own",
"Half From NIH, Half From Everywhere Else",
"Controlling the Message",
"Bacteria Under Pressure",
"Two Laboratories That Chose Each Other",
"Tolerance, Damage and Transmission",
"Viruses as Targets, Sensors and Tools",
"And One More, Who Hasn't Started Yet",
"Some of you lost grants",
"…but both things can be true",
"A New Dean, and a Renewed Bet on Basic Science",
"$30 Million from Jan Vilcek",
"The Clinical Interface Is Becoming Operational",
"Pathogen Immunology As a New Connective Layer",
"The Problem We Have in Common",
"Renovations Are (Almost) Finished",
"Every Shared Instrument, Now in One Place",
"Helping the Community Find Funding",
"The Quarterly Newsletter",
"Every Lab Has a Liaison",
"And If You Would Rather Tell Me Yourself",
"The Seminar Series Is How We Widen the Circle",
"The Whole Year Is Online, and It Is Not Finished",
"Two Clubs, and Anyone Can Walk In",
"Add These in Your Calendar",
"And the People Who Actually Run This Department",
"This year does not get the credit for our success. We do.",
"Thank you"
];
